"""rename_topic_to_title_on_schedule

Revision ID: 42a80b1531a8
Revises: 9aab76dd5632
Create Date: 2025-11-24 00:10:53.577874

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "42a80b1531a8"
down_revision: Union[str, None] = "9aab76dd5632"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("schedule", "topic", new_column_name="title")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("schedule", "title", new_column_name="topic")
    # ### end Alembic commands ###
