"""add google id and google email on user

Revision ID: 1788b33307f3
Revises: d1567689c00d
Create Date: 2025-09-22 21:08:41.262717

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1788b33307f3"
down_revision: Union[str, None] = "d1567689c00d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("google_id", sa.String(length=255), nullable=True))
    op.add_column(
        "user", sa.Column("google_email", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_public_user_google_id"),
        "user",
        ["google_id"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_public_user_google_id"), table_name="user", schema="public")
    op.drop_column("user", "google_email")
    op.drop_column("user", "google_id")
    # ### end Alembic commands ###
