"""alter schedule speaker to nullable

Revision ID: b643409f7fa7
Revises: 26760cbe21a5
Create Date: 2025-12-02 21:17:04.691789

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b643409f7fa7"
down_revision: Union[str, None] = "26760cbe21a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("schedule", "speaker_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("schedule", "speaker_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
