"""create table stream

Revision ID: 322b554e2927
Revises: c4cc3804ceda
Create Date: 2025-11-04 20:08:57.681574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "322b554e2927"
down_revision: Union[str, None] = "c4cc3804ceda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stream_asset",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=True),
        sa.Column("mux_asset_id", sa.String(length=255), nullable=True),
        sa.Column("mux_playback_id", sa.String(length=255), nullable=True),
        sa.Column("mux_signed_playback_id", sa.String(length=255), nullable=True),
        sa.Column("mux_live_stream_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("is_live", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "READY",
                "STREAMING",
                "ENDED",
                "FAILED",
                name="streamstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "duration", sa.Integer(), nullable=True, comment="Duration in seconds"
        ),
        sa.Column("thumbnail_url", sa.String(length=500), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("max_concurrent_viewers", sa.Integer(), nullable=False),
        sa.Column("stream_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stream_ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["public.schedule.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_asset_id"),
        "stream_asset",
        ["id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_asset_is_live"),
        "stream_asset",
        ["is_live"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_asset_is_public"),
        "stream_asset",
        ["is_public"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_asset_mux_asset_id"),
        "stream_asset",
        ["mux_asset_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_asset_mux_live_stream_id"),
        "stream_asset",
        ["mux_live_stream_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_asset_mux_playback_id"),
        "stream_asset",
        ["mux_playback_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_asset_mux_signed_playback_id"),
        "stream_asset",
        ["mux_signed_playback_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_asset_schedule_id"),
        "stream_asset",
        ["schedule_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_asset_status"),
        "stream_asset",
        ["status"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "stream_view",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stream_asset_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "duration_watched",
            sa.Integer(),
            nullable=False,
            comment="Duration watched in seconds",
        ),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["stream_asset_id"],
            ["public.stream_asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_view_id"),
        "stream_view",
        ["id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_view_stream_asset_id"),
        "stream_view",
        ["stream_asset_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_view_user_id"),
        "stream_view",
        ["user_id"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_stream_view_user_id"), table_name="stream_view", schema="public"
    )
    op.drop_index(
        op.f("ix_public_stream_view_stream_asset_id"),
        table_name="stream_view",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_stream_view_id"), table_name="stream_view", schema="public"
    )
    op.drop_table("stream_view", schema="public")
    op.drop_index(
        op.f("ix_public_stream_asset_status"),
        table_name="stream_asset",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_stream_asset_schedule_id"),
        table_name="stream_asset",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_stream_asset_mux_signed_playback_id"),
        table_name="stream_asset",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_stream_asset_mux_playback_id"),
        table_name="stream_asset",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_stream_asset_mux_live_stream_id"),
        table_name="stream_asset",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_stream_asset_mux_asset_id"),
        table_name="stream_asset",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_stream_asset_is_public"),
        table_name="stream_asset",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_stream_asset_is_live"),
        table_name="stream_asset",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_stream_asset_id"), table_name="stream_asset", schema="public"
    )
    op.drop_table("stream_asset", schema="public")
    # ### end Alembic commands ###
