"""remove slide title and add stream key

Revision ID: fd7a3df82b39
Revises: 42a80b1531a8
Create Date: 2025-11-25 19:35:00.184433

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fd7a3df82b39"
down_revision: Union[str, None] = "42a80b1531a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "slide_title")
    op.add_column(
        "stream", sa.Column("mux_stream_key", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_public_stream_mux_stream_key"),
        "stream",
        ["mux_stream_key"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_stream_mux_stream_key"), table_name="stream", schema="public"
    )
    op.drop_column("stream", "mux_stream_key")
    op.add_column(
        "schedule",
        sa.Column("slide_title", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
