"""change speaker to link with user

Revision ID: e4b791d43166
Revises: 111a12914a0a
Create Date: 2025-11-18 08:12:43.547102

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4b791d43166"
down_revision: Union[str, None] = "111a12914a0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("speaker", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        "speaker_user_id_fkey",
        "speaker",
        "user",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_column("speaker", "photo_url")
    op.drop_column("speaker", "email")
    op.drop_column("speaker", "name")
    op.drop_column("speaker", "bio")
    op.drop_column("speaker", "x_link")
    op.drop_column("speaker", "instagram_link")
    op.drop_column("speaker", "is_keynote_speaker")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "speaker",
        sa.Column("instagram_link", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "speaker", sa.Column("x_link", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "speaker", sa.Column("bio", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "speaker", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "speaker", sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "speaker",
        sa.Column("photo_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "speaker",
        sa.Column(
            "is_keynote_speaker", sa.Boolean(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(
        "speaker_user_id_fkey", "speaker", schema="public", type_="foreignkey"
    )
    op.drop_column("speaker", "user_id")
    # ### end Alembic commands ###
