"""Add mux_asset_id and mux_asset_playback_id to stream table

Revision ID: 3a190131d228
Revises: fd7a3df82b39
Create Date: 2025-11-25 20:10:58.959041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3a190131d228"
down_revision: Union[str, None] = "fd7a3df82b39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stream", sa.Column("mux_asset_id", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "stream",
        sa.Column("mux_asset_playback_id", sa.String(length=255), nullable=True),
    )
    op.create_index(
        op.f("ix_public_stream_mux_asset_id"),
        "stream",
        ["mux_asset_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stream_mux_asset_playback_id"),
        "stream",
        ["mux_asset_playback_id"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_stream_mux_asset_playback_id"),
        table_name="stream",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_stream_mux_asset_id"), table_name="stream", schema="public"
    )
    op.drop_column("stream", "mux_asset_playback_id")
    op.drop_column("stream", "mux_asset_id")
    # ### end Alembic commands ###
