"""Add attendance_updated_by_to_user

Revision ID: 643d2c34e927
Revises: b3212d6ebfde
Create Date: 2025-11-28 22:11:40.241732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "643d2c34e927"
down_revision: Union[str, None] = "b3212d6ebfde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("attendance_day_1_updated_by", sa.UUID(), nullable=True)
    )
    op.add_column(
        "user", sa.Column("attendance_day_2_updated_by", sa.UUID(), nullable=True)
    )

    op.create_foreign_key(
        "fk_user_attendance_day_1_updated_by",
        "user",
        "user",
        ["attendance_day_1_updated_by"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        "fk_user_attendance_day_2_updated_by",
        "user",
        "user",
        ["attendance_day_2_updated_by"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_user_attendance_day_2_updated_by",
        "user",
        type_="foreignkey",
        schema="public",
    )
    op.drop_constraint(
        "fk_user_attendance_day_1_updated_by",
        "user",
        type_="foreignkey",
        schema="public",
    )
    op.drop_column("user", "attendance_day_2_updated_by")
    op.drop_column("user", "attendance_day_1_updated_by")
    # ### end Alembic commands ###
