"""add column github id and username

Revision ID: cbcea4ed4b3a
Revises: 250b56a10ce6
Create Date: 2025-07-16 18:22:55.636277

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cbcea4ed4b3a"
down_revision: Union[str, None] = "250b56a10ce6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("github_id", sa.String(length=255), nullable=True))
    op.add_column(
        "user", sa.Column("github_username", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_public_user_github_id"),
        "user",
        ["github_id"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_public_user_github_id"), table_name="user", schema="public")
    op.drop_column("user", "github_username")
    op.drop_column("user", "github_id")
    # ### end Alembic commands ###
