"""add some new columns user

Revision ID: 1f29f50ed6be
Revises: 1788b33307f3
Create Date: 2025-09-27 19:46:30.695898

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f29f50ed6be"
down_revision: Union[str, None] = "1788b33307f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("profile_picture", sa.String(), nullable=True))
    op.add_column("user", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("last_name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("email", sa.String(), nullable=True))
    op.add_column("user", sa.Column("industry_categories", sa.String(), nullable=True))
    op.add_column("user", sa.Column("company", sa.String(), nullable=True))
    op.add_column("user", sa.Column("job_category", sa.String(), nullable=True))
    op.add_column("user", sa.Column("job_title", sa.String(), nullable=True))
    op.add_column("user", sa.Column("experience", sa.String(), nullable=True))
    op.add_column("user", sa.Column("t_shirt_size", sa.String(), nullable=True))
    op.add_column("user", sa.Column("gender", sa.String(), nullable=True))
    op.add_column("user", sa.Column("date_of_birth", sa.String(), nullable=True))
    op.add_column("user", sa.Column("phone", sa.String(), nullable=True))
    op.add_column("user", sa.Column("country", sa.String(), nullable=True))
    op.add_column("user", sa.Column("state", sa.String(), nullable=True))
    op.add_column("user", sa.Column("city", sa.String(), nullable=True))
    op.add_column("user", sa.Column("zip_code", sa.String(), nullable=True))
    op.add_column("user", sa.Column("address", sa.String(), nullable=True))
    op.add_column("user", sa.Column("bio", sa.String(), nullable=True))
    op.add_column("user", sa.Column("interest", sa.String(), nullable=True))
    op.add_column("user", sa.Column("looking_for", sa.String(), nullable=True))
    op.add_column("user", sa.Column("expertise", sa.String(), nullable=True))
    op.add_column("user", sa.Column("website", sa.String(), nullable=True))
    op.add_column("user", sa.Column("facebook_username", sa.String(), nullable=True))
    op.add_column("user", sa.Column("linkedin_username", sa.String(), nullable=True))
    op.add_column("user", sa.Column("twitter_username", sa.String(), nullable=True))
    op.add_column("user", sa.Column("instagram_username", sa.String(), nullable=True))
    op.add_column("user", sa.Column("terms_agreed", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("privacy_agreed", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("coc_acknowledged", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("participant_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### end Alembic commands ###
