"""add voucher_id to payment table

Revision ID: 70f512a9c9b6
Revises: 3f255debcd19
Create Date: 2025-11-13 21:43:55.569714

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70f512a9c9b6"
down_revision: Union[str, None] = "3f255debcd19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment", sa.Column("voucher_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_public_payment_voucher_id"),
        "payment",
        ["voucher_id"],
        unique=False,
        schema="public",
    )
    op.create_foreign_key(
        "fk_payment_voucher_id",
        "payment",
        "voucher",
        ["voucher_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_payment_voucher_id", "payment", schema="public", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_public_payment_voucher_id"), table_name="payment", schema="public"
    )
    op.drop_column("payment", "voucher_id")
    # ### end Alembic commands ###
