"""create_streaming_table_and_refactor_schedule

Revision ID: 9aab76dd5632
Revises: e4b791d43166
Create Date: 2025-11-23 14:34:21.135438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9aab76dd5632'
down_revision: Union[str, None] = 'e4b791d43166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_room_id'), 'room', ['id'], unique=False, schema='public')
    op.create_table('schedule_type',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_schedule_type_id'), 'schedule_type', ['id'], unique=False, schema='public')
    op.create_table('stream',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('schedule_id', sa.UUID(), nullable=False),
        sa.Column('mux_playback_id', sa.String(length=255), nullable=True),
        sa.Column('mux_live_stream_id', sa.String(length=255), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('stream_started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('stream_ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['schedule_id'], ['public.schedule.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_stream_id'), 'stream', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_stream_is_public'), 'stream', ['is_public'], unique=False, schema='public')
    op.create_index(op.f('ix_public_stream_mux_live_stream_id'), 'stream', ['mux_live_stream_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_stream_mux_playback_id'), 'stream', ['mux_playback_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_stream_schedule_id'), 'stream', ['schedule_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_stream_status'), 'stream', ['status'], unique=False, schema='public')
    op.add_column('schedule', sa.Column('room_id', sa.UUID(), nullable=True))
    op.add_column('schedule', sa.Column('schedule_type_id', sa.UUID(), nullable=True))
    op.add_column('schedule', sa.Column('presentation_language', sa.String(), nullable=True))
    op.add_column('schedule', sa.Column('slide_language', sa.String(), nullable=True))
    op.add_column('schedule', sa.Column('slide_title', sa.String(), nullable=True))
    op.add_column('schedule', sa.Column('slide_link', sa.String(), nullable=True))
    op.add_column('schedule', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.create_index(op.f('ix_public_schedule_room_id'), 'schedule', ['room_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_schedule_schedule_type_id'), 'schedule', ['schedule_type_id'], unique=False, schema='public')
    op.create_foreign_key('fk_schedule_room_id', 'schedule', 'room', ['room_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_schedule_schedule_type_id', 'schedule', 'schedule_type', ['schedule_type_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_column('schedule', 'stream_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('stream_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_schedule_room_id', 'schedule', schema='public', type_='foreignkey')
    op.drop_constraint('fk_schedule_schedule_type_id', 'schedule', schema='public', type_='foreignkey')
    op.drop_index(op.f('ix_public_schedule_schedule_type_id'), table_name='schedule', schema='public')
    op.drop_index(op.f('ix_public_schedule_room_id'), table_name='schedule', schema='public')
    op.drop_column('schedule', 'tags')
    op.drop_column('schedule', 'slide_link')
    op.drop_column('schedule', 'slide_title')
    op.drop_column('schedule', 'slide_language')
    op.drop_column('schedule', 'presentation_language')
    op.drop_column('schedule', 'schedule_type_id')
    op.drop_column('schedule', 'room_id')
    op.drop_index(op.f('ix_public_stream_status'), table_name='stream', schema='public')
    op.drop_index(op.f('ix_public_stream_schedule_id'), table_name='stream', schema='public')
    op.drop_index(op.f('ix_public_stream_mux_playback_id'), table_name='stream', schema='public')
    op.drop_index(op.f('ix_public_stream_mux_live_stream_id'), table_name='stream', schema='public')
    op.drop_index(op.f('ix_public_stream_is_public'), table_name='stream', schema='public')
    op.drop_index(op.f('ix_public_stream_id'), table_name='stream', schema='public')
    op.drop_table('stream', schema='public')
    op.drop_index(op.f('ix_public_schedule_type_id'), table_name='schedule_type', schema='public')
    op.drop_table('schedule_type', schema='public')
    op.drop_index(op.f('ix_public_room_id'), table_name='room', schema='public')
    op.drop_table('room', schema='public')
    # ### end Alembic commands ###
