"""create payment table

Revision ID: 08dc2023813d
Revises: e338d029d3e2
Create Date: 2025-10-15 20:50:38.302143

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08dc2023813d"
down_revision: Union[str, None] = "e338d029d3e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("payment_link", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mayar_id", sa.String(), nullable=True),
        sa.Column("mayar_transaction_id", sa.String(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["public.ticket.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_payment_id"), "payment", ["id"], unique=False, schema="public"
    )
    op.create_index(
        op.f("ix_public_payment_mayar_id"),
        "payment",
        ["mayar_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_payment_mayar_transaction_id"),
        "payment",
        ["mayar_transaction_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_payment_ticket_id"),
        "payment",
        ["ticket_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_payment_user_id"),
        "payment",
        ["user_id"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_payment_user_id"), table_name="payment", schema="public"
    )
    op.drop_index(
        op.f("ix_public_payment_ticket_id"), table_name="payment", schema="public"
    )
    op.drop_index(
        op.f("ix_public_payment_mayar_transaction_id"),
        table_name="payment",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_payment_mayar_id"), table_name="payment", schema="public"
    )
    op.drop_index(op.f("ix_public_payment_id"), table_name="payment", schema="public")
    op.drop_table("payment", schema="public")
    # ### end Alembic commands ###
