"""create table speaker_type and link with speaker

Revision ID: 111a12914a0a
Revises: 70f512a9c9b6
Create Date: 2025-11-16 09:43:05.746184

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "111a12914a0a"
down_revision: Union[str, None] = "70f512a9c9b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "speaker_type",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.add_column("speaker", sa.Column("speaker_type_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "speaker_speaker_type_id_fkey",
        "speaker",
        "speaker_type",
        ["speaker_type_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "speaker_speaker_type_id_fkey", "speaker", schema="public", type_="foreignkey"
    )
    op.drop_column("speaker", "speaker_type_id")
    op.drop_table("speaker_type", schema="public")
    # ### end Alembic commands ###
