"""create table accounts

Revision ID: a3ed57dc827b
Revises: 250b56a10ce6
Create Date: 2025-07-15 21:39:29.442963

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3ed57dc827b"
down_revision: Union[str, None] = "250b56a10ce6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=False),
        sa.Column("provider_email", sa.String(length=255), nullable=True),
        sa.Column("provider_username", sa.String(length=255), nullable=True),
        sa.Column("provider_name", sa.String(length=255), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("token_type", sa.Text(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_account_id"), "account", ["id"], unique=False, schema="public"
    )
    op.create_index(
        op.f("ix_public_account_provider_id"),
        "account",
        ["provider_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_account_user_id"),
        "account",
        ["user_id"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_account_user_id"), table_name="account", schema="public"
    )
    op.drop_index(
        op.f("ix_public_account_provider_id"), table_name="account", schema="public"
    )
    op.drop_index(op.f("ix_public_account_id"), table_name="account", schema="public")
    op.drop_table("account", schema="public")
    # ### end Alembic commands ###
