"""add some column on table user

Revision ID: 2804c0cd6ed9
Revises: c4cc3804ceda
Create Date: 2025-11-07 09:55:24.551365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2804c0cd6ed9"
down_revision: Union[str, None] = "c4cc3804ceda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("share_my_email_and_phone_number", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "user", sa.Column("share_my_job_and_company", sa.Boolean(), nullable=True)
    )
    op.add_column("user", sa.Column("share_my_location", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("share_my_interest", sa.Boolean(), nullable=True))
    op.add_column(
        "user", sa.Column("share_my_public_social_media", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "share_my_public_social_media")
    op.drop_column("user", "share_my_interest")
    op.drop_column("user", "share_my_location")
    op.drop_column("user", "share_my_job_and_company")
    op.drop_column("user", "share_my_email_and_phone_number")
    # ### end Alembic commands ###
