"""create table email verification

Revision ID: 5426fd033deb
Revises: 437d5241b4a7
Create Date: 2025-10-02 07:47:08.055064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5426fd033deb"
down_revision: Union[str, None] = "437d5241b4a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("verification_code", sa.String(), nullable=False),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_email_verification_email"),
        "email_verification",
        ["email"],
        unique=True,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_email_verification_id"),
        "email_verification",
        ["id"],
        unique=False,
        schema="public",
    )
    op.drop_index("ix_refresh_token_id", table_name="refresh_token")
    op.drop_index("ix_refresh_token_user_id", table_name="refresh_token")
    op.create_index(
        op.f("ix_public_refresh_token_id"),
        "refresh_token",
        ["id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_refresh_token_user_id"),
        "refresh_token",
        ["user_id"],
        unique=False,
        schema="public",
    )
    op.drop_constraint(
        "refresh_token_user_id_fkey", "refresh_token", type_="foreignkey"
    )
    op.drop_constraint(
        "refresh_token_token_id_fkey", "refresh_token", type_="foreignkey"
    )
    op.create_foreign_key(
        "refresh_token_token_id_fkey",
        "refresh_token",
        "token",
        ["token_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "refresh_token_user_id_fkey",
        "refresh_token",
        "user",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.alter_column(
        "ticket",
        "description",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_public_ticket_id"), "ticket", ["id"], unique=False, schema="public"
    )
    op.drop_index("ix_token_id", table_name="token")
    op.drop_index("ix_token_user_id", table_name="token")
    op.create_index(
        op.f("ix_public_token_id"), "token", ["id"], unique=False, schema="public"
    )
    op.create_index(
        op.f("ix_public_token_user_id"),
        "token",
        ["user_id"],
        unique=False,
        schema="public",
    )
    op.drop_constraint("token_user_id_fkey", "token", type_="foreignkey")
    op.create_foreign_key(
        "token_user_id_fkey",
        "token",
        "user",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_index("ix_user_id", table_name="user")
    op.create_index(
        op.f("ix_public_user_id"), "user", ["id"], unique=False, schema="public"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_public_user_id"), table_name="user", schema="public")
    op.create_index("ix_user_id", "user", ["id"], unique=False)
    op.drop_constraint(
        "token_user_id_fkey", "token", schema="public", type_="foreignkey"
    )
    op.create_foreign_key("token_user_id_fkey", "token", "user", ["user_id"], ["id"])
    op.drop_index(op.f("ix_public_token_user_id"), table_name="token", schema="public")
    op.drop_index(op.f("ix_public_token_id"), table_name="token", schema="public")
    op.create_index("ix_token_user_id", "token", ["user_id"], unique=False)
    op.create_index("ix_token_id", "token", ["id"], unique=False)
    op.drop_index(op.f("ix_public_ticket_id"), table_name="ticket", schema="public")
    op.alter_column(
        "ticket",
        "description",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_constraint(
        "refresh_token_user_id_fkey",
        "refresh_token",
        schema="public",
        type_="foreignkey",
    )
    op.drop_constraint(
        "refresh_token_token_id_fkey",
        "refresh_token",
        schema="public",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "refresh_token_token_id_fkey",
        "refresh_token",
        "token",
        ["token_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "refresh_token_user_id_fkey", "refresh_token", "user", ["user_id"], ["id"]
    )
    op.drop_index(
        op.f("ix_public_refresh_token_user_id"),
        table_name="refresh_token",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_refresh_token_id"), table_name="refresh_token", schema="public"
    )
    op.create_index(
        "ix_refresh_token_user_id", "refresh_token", ["user_id"], unique=False
    )
    op.create_index("ix_refresh_token_id", "refresh_token", ["id"], unique=False)
    op.drop_index(
        op.f("ix_public_email_verification_id"),
        table_name="email_verification",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_email_verification_email"),
        table_name="email_verification",
        schema="public",
    )
    op.drop_table("email_verification", schema="public")
    # ### end Alembic commands ###
